--Add Foreign key
ALTER TABLE User_Contact ADD FOREIGN KEY(NIC) REFERENCES User(NIC);
ALTER TABLE Admin ADD FOREIGN KEY(NIC) REFERENCES User(NIC);
ALTER TABLE Dean ADD FOREIGN KEY(NIC) REFERENCES User(NIC);
ALTER TABLE Student ADD FOREIGN KEY(NIC) REFERENCES User(NIC);